server:
  port: 8080
  servlet:
    context-path: /tijian

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/physical_examination?characterEncoding=utf-8
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  typeAliasesPackage: edu.scau.tijian.pojo, edu.scau.tijian.dto

logging:
  level:
    org.springframework: info
    edu.scau.tijian.mapper: debug